### PR TITLE
Updated changelog, notifier version

### PR DESCRIPTION
**Pull request by chimanjain**

### CODE REVIEW

**Comment by kyrylo** [comment]
Is this a release? We should update this only when we are about to release.

**Comment by kyrylo** [comment]
Please make it clear in the commit message. Example commit: https://github.com/airbrake/gobrake/commit/841d8f81fc523bce6283abfbfc5def04f8130c35

**Comment by chimanjain** [comment]
I will be updating the changelog in a separate commit.

**Comment by chimanjain** [comment]
PTAL

**Pull request merged**
